# This file acts as the base configuration file for the project.

# used for logging
project_name: "template"

# used for naming purposes
note: "note"

robot_parameters:
  verbose: False

# device on which to train
device: "cuda"

# scans
pre_scanned_graphs:
  base_fiducial_id: 101
  graph_frame_name_prefix: "filtered_fiducial_"
  floor: -0.1

  # low_res: "2025_10_17"
  # high_res: "2025_10_17"
  # masked: "2025_10_17"

  # low_res: "2025_09_12"
  # high_res: "2025_09_12"
  # masked: "2025_09_12"

  # low_res: "2025_09_15"
  # high_res: "2025_09_15"
  # masked: "2025_09_15"

  # low_res: "2025_11_20"
  # high_res: "2025_11_20"
  # masked: "2025_11_20"

  # low_res: "2025_11_25"
  # high_res: "2025_11_25"
  # masked: "2025_11_25"

  # low_res: "2025_11_27"
  # high_res: "2025_11_27"
  # masked: "2025_11_27"

  # low_res: "2025_12_12"
  # high_res: "2025_12_12"
  # masked: "2025_12_12"

  # low_res: "2026_01_16"
  # high_res: "2026_01_16"
  # masked: "2026_01_16"

  # low_res: "2026_01_22"
  # high_res: "2026_01_22"
  # masked: "2026_01_22"
  
  # low_res: "2026_02_20"
  # high_res: "2026_02_20"
  # masked: "2026_02_20"

  # low_res: "2026_02_24"  # Old
  # high_res: "2026_02_24"
  # masked: "2026_02_24"

  # low_res: "2026_02_25" # Old
  # high_res: "2026_02_25"
  # masked: "2026_02_25"

  # low_res: "2026_03_03"
  # high_res: "2026_03_03"
  # masked: "2026_03_03"

  # low_res: "2026_03_13_Gokul"
  # high_res: "2026_03_13_Gokul"
  # masked: "2026_03_13_Gokul"

  # low_res: "2026_03_13_test"
  # high_res: "2026_03_13_test"
  # masked: "2026_03_13_test"

  # low_res: "2026_03_18"
  # high_res: "2026_03_18"
  # masked: "2026_03_18"

  # low_res: "2026_03_19"
  # high_res: "2026_03_19"
  # masked: "2026_03_19"

  low_res: "2026_03_26"
  high_res: "2026_03_26"
  masked: "2026_03_26"

# paths are relative from project_root_directory
subpaths:
  cache: "cache/"
  logs: "data/logs/"
  output: "output/"
  resume_from: "path/to/weights"
  data: "data/"
  aligned_point_clouds: "data/aligned_point_clouds"
  autowalk_scans: "data/autowalk_scans"
  images: "data/images"
  ipad_scans: "data/ipad_scans"
  merged_point_clouds: "data/merged_point_clouds"
  openmask_features: "data/openmask_features"
  scene_graph: "data/scene_graph"
  stretch_description: "data/stretch_description"
  masks: "data/ipad_scans"
  # environment
  environment: ".environment.yaml"
  tmp: "data/tmp"

# dockers
servers:
  graspnet:
    ip: "127.0.0.1"
    port: 5000
    route: "graspnet/predict"
  openmask:
    ip: "127.0.0.1"
    port: 5001
    route: "openmask/save_and_predict"
  vitpose:
    ip: "127.0.0.1"
    port: 5002
    route: "vitpose/predict"
  darknet:
    ip: "127.0.0.1"
    port: 5003
    route: "darknet/predict"
  yolodrawer:
    ip: "127.0.0.1"
    port: 5004
    route: "yolodrawer/predict"